### ISSUE TITLE
Handling possibly sparse arrays

### ISSUE THREAD

**Issue by tkf** [JuliaGPU/Adapt.jl#19]
Currently, converting a matrix that could be dense or sparse requires explicit branching:

```julia
if x isa SparseMatrixCSC
    # adapt(CuSparseMatrixCSC, x) does not work, BTW
    CuSparseMatrixCSC(x)
else
    adapt(CuArray, x)
end
```

It would be nice if `adapt` can do something like

```julia
to = Union{CuArray, CuSparseMatrixCSC, CuSparseMatrixCSR}

adapt(to, zeros(2, 2)) :: CuArray
adapt(to, spzeros(2, 2)) :: CuSparseMatrixCSC
adapt(to, transpose(spzeros(2, 2))) :: CuSparseMatrixCSR
```

Is it in the scope of this package?

**Comment by MikeInnes** [comment]
I think it'd be fine for `adapt(CuArray, x)` to support sparse arrays like this. However, that would have to happen in CuArrays.jl, not adapt.jl itself.

**Comment by tkf** [comment]
Thanks for the clarification. So I'll close this issue for now. Maybe I'll open a PR in CuArrays.jl later.
