### ISSUE TITLE
Reason for missing LinearAlgebra wrappers?

### ISSUE THREAD

**Issue by danielwe** [JuliaGPU/Adapt.jl#46]
Is there a reason the WrappedArray union omits some of the basic array wrappers from LinearAlgebra, specifically Symmetric, Hermitian, UpperHessenberg, SymTridiagonal, and Bidiagonal? I know at least symmetric and hermitian matrices have good CUSOLVER support (even if CUDA.jl doesn't wrap everything yet), so at least from the GPU perspective, I don't see an obvious reason why these wouldn't be treated the same as other wrappers.

**Comment by maleadt** [comment]
No reason, PRs welcome :slightly_smiling_face:
