### ISSUE TITLE
LoadError: ArgumentError: Package AdaptStaticArraysCoreExt does not have Adapt in its dependencies

### ISSUE THREAD

**Issue by chengchingwen** [JuliaGPU/Adapt.jl#61]
I get an error about the package extension with Adapt v3.6 on julia-1.9beta4

**Comment by anandijain** [comment]
thanks!

**Comment by StackEnjoyer** [comment]
I can also report this issue with v3.6.0 where during precompiling an error occurs regarding AdaptStaticArraysExt. Downgrading to v3.5.0 resolves this for me.
